BINDING_HEADER_MINARCH_HEADER = "Minimal Archaeology"
BINDING_NAME_MINARCH_SHOWHIDE = "Show/Hide Minimal Archaeology"
setglobal("BINDING_NAME_SPELL Survey", "Survey")

ARCHAEOLOGY_RACE_DEMONIC             = 1
ARCHAEOLOGY_RACE_HIGHMOUNTAIN_TAUREN = 2
ARCHAEOLOGY_RACE_HIGHBORNE           = 3
ARCHAEOLOGY_RACE_OGRE                = 4
ARCHAEOLOGY_RACE_DRAENOR             = 5
ARCHAEOLOGY_RACE_ARAKKOA             = 6
ARCHAEOLOGY_RACE_MOGU                = 7
ARCHAEOLOGY_RACE_PANDAREN            = 8
ARCHAEOLOGY_RACE_MANTID              = 9
ARCHAEOLOGY_RACE_VRYKUL              = 10
ARCHAEOLOGY_RACE_TROLL               = 11
ARCHAEOLOGY_RACE_TOLVIR              = 12
ARCHAEOLOGY_RACE_ORC                 = 13
ARCHAEOLOGY_RACE_NERUBIAN            = 14
ARCHAEOLOGY_RACE_NIGHTELF            = 15
ARCHAEOLOGY_RACE_FOSSIL              = 16
ARCHAEOLOGY_RACE_DRAENEI             = 17
ARCHAEOLOGY_RACE_DWARF               = 18