MINARCH_EXPANSION = 'Mop'

-- uiMapIDs for continents [uiMapID] = internalContID
MinArchContIDMap = {
	[1414] = 1, -- Kalimdor
	[1415] = 2, -- EK
	[1945] = 3, -- Outland
	[113] = 4, -- Northrend
	[948] = 5, -- Maelstrom
	[424] = 6, -- Pandaria
};

ARCHAEOLOGY_RACE_DRUSTVARI           = 0
ARCHAEOLOGY_RACE_ZANDALARI           = 0
ARCHAEOLOGY_RACE_DEMONIC             = 0
ARCHAEOLOGY_RACE_HIGHMOUNTAIN_TAUREN = 0
ARCHAEOLOGY_RACE_HIGHBORNE           = 0
ARCHAEOLOGY_RACE_OGRE                = 0
ARCHAEOLOGY_RACE_DRAENOR             = 0
ARCHAEOLOGY_RACE_ARAKKOA             = 0
ARCHAEOLOGY_RACE_MOGU                = 1
ARCHAEOLOGY_RACE_PANDAREN            = 2
ARCHAEOLOGY_RACE_MANTID              = 3
ARCHAEOLOGY_RACE_VRYKUL              = 4
ARCHAEOLOGY_RACE_TROLL               = 5
ARCHAEOLOGY_RACE_TOLVIR              = 6
ARCHAEOLOGY_RACE_ORC                 = 7
ARCHAEOLOGY_RACE_NERUBIAN            = 8
ARCHAEOLOGY_RACE_NIGHTELF            = 9
ARCHAEOLOGY_RACE_FOSSIL              = 10
ARCHAEOLOGY_RACE_DRAENEI             = 11
ARCHAEOLOGY_RACE_DWARF               = 12

ARCHAEOLOGY_NUM_RACES                = 12
ARCHAEOLOGY_NUM_CONTINENTS           = 6
ARCHAEOLOGY_MAX_RANK				 = 525

MINARCH_MSG_STATUS = nil
MINARCH_MSG_DEBUG = 1

SURVEY_SPELL_ID = 80451

MINARCH_QSTATE_NIL = 0;
MINARCH_QSTATE_LEGION_AVAILABLE    = 1;
MINARCH_QSTATE_PRISTINE_INCOMPLETE = 2;
MINARCH_QSTATE_PRISTINE_ONQUEST    = 3;
MINARCH_QSTATE_PRISTINE_COMPLETE   = 4;

MINARCH_PROGRESS_UNKNOWN        = 0;
MINARCH_PROGRESS_KNOWN          = 1;
MINARCH_PROGRESS_CURRENT        = 2;
MINARCH_ACHIPROGRESS_NONE       = 3;
MINARCH_ACHIPROGRESS_INCOMPLETE = 4;
MINARCH_ACHIPROGRESS_COMPLETE   = 5;
