ARCHAEOLOGY_RACE_VRYKUL              = 1
ARCHAEOLOGY_RACE_TROLL               = 2
ARCHAEOLOGY_RACE_TOLVIR              = 3
ARCHAEOLOGY_RACE_ORC                 = 4
ARCHAEOLOGY_RACE_NERUBIAN            = 5
ARCHAEOLOGY_RACE_NIGHTELF            = 6
ARCHAEOLOGY_RACE_FOSSIL              = 7
ARCHAEOLOGY_RACE_DRAENEI             = 8
ARCHAEOLOGY_RACE_DWARF               = 9

ARCHAEOLOGY_NUM_RACES                = 9
ARCHAEOLOGY_NUM_CONTINENTS           = 5

MINARCH_MSG_STATUS = nil
MINARCH_MSG_DEBUG = 1

SURVEY_SPELL_ID = 80451

MINARCH_QSTATE_NIL = 0;
MINARCH_QSTATE_LEGION_AVAILABLE    = 1;
MINARCH_QSTATE_PRISTINE_INCOMPLETE = 2;
MINARCH_QSTATE_PRISTINE_ONQUEST    = 3;
MINARCH_QSTATE_PRISTINE_COMPLETE   = 4;

MINARCH_PROGRESS_UNKNOWN        = 0;
MINARCH_PROGRESS_KNOWN          = 1;
MINARCH_PROGRESS_CURRENT        = 2;
MINARCH_ACHIPROGRESS_NONE       = 3;
MINARCH_ACHIPROGRESS_INCOMPLETE = 4;
MINARCH_ACHIPROGRESS_COMPLETE   = 5;
